services:

  postgres:
    image: postgres:16
    container_name: postgres_cnpj

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cnpj_db

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5


  api:
    build: .
    container_name: api_cnpj

    ports:
      - "8000:8000"

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/cnpj_db

    command: >
      sh -c "
      alembic upgrade head &&
      uvicorn main:app --host 0.0.0.0 --port 8000
      "

volumes:
  postgres_data:
