"""adiciona auditoria empresas

Revision ID: 86881d3be44c
Revises: c555169dbf3c
Create Date: 2026-05-28 11:37:12.187264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86881d3be44c'
down_revision: Union[str, Sequence[str], None] = 'c555169dbf3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('criado_em', sa.DateTime(), nullable=True))
    op.add_column('empresas', sa.Column('atualizado_em', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresas', 'atualizado_em')
    op.drop_column('empresas', 'criado_em')
    # ### end Alembic commands ###
