"""adiciona soft delete

Revision ID: c555169dbf3c
Revises: 412132902956
Create Date: 2026-05-27 12:25:18.787029

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c555169dbf3c"
down_revision: Union[str, Sequence[str], None] = "412132902956"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("empresas", sa.Column("ativo", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("empresas", "ativo")
    # ### end Alembic commands ###
